const PROJECTS = [
  {
    title: "American Horizon",
    description: "Corporate website for a moving company with modern responsive design and clear service navigation.",
    url: "https://secford.github.io/MoveCompany-Website/",
    image: "https://placehold.co/600x400/111837/4facfe?text=American+Horizon",
    tags: ["HTML", "CSS", "JS"],
  },
  {
    title: "Ashwood Hideaway",
    description: "Landing page for a premium retreat with immersive hero section and elegant typography.",
    url: "https://secford.github.io/LandigSite/",
    image: "https://placehold.co/600x400/0a0e27/00f2fe?text=Ashwood+Hideaway",
    tags: ["HTML", "CSS", "JS"],
  },
  {
    title: "Dumpling Kingdom",
    description: "Restaurant website with mouth-watering gallery, menu layout, and location info.",
    url: "https://secford.github.io/DumplingKindom-website/",
    image: "https://placehold.co/600x400/1a2248/6c8cff?text=Dumpling+Kingdom",
    tags: ["HTML", "CSS", "JS"],
  },
  {
    title: "Haunting Hawk Golf Club",
    description: "Golf club landing page showcasing the course, amenities, and membership options.",
    url: "https://secford.github.io/Golf-website/",
    image: "https://placehold.co/600x400/111837/4facfe?text=Golf+Club",
    tags: ["HTML", "CSS", "JS"],
  },
  {
    title: "EpesAi",
    description: "AI service landing page with modern layout, feature sections, and API integration.",
    url: "https://secford.github.io/EpesAi-site/",
    image: "https://placehold.co/600x400/0a0e27/00f2fe?text=EpesAi",
    tags: ["HTML", "CSS", "JS", "API"],
  },
  {
    title: "Allianz Insurance",
    description: "Insurance brand landing page with structured content blocks and trust signals.",
    url: "https://secford.github.io/Allianz-site/",
    image: "https://placehold.co/600x400/1a2248/6c8cff?text=Allianz+Insurance",
    tags: ["HTML", "CSS", "JS"],
  },
  {
    title: "Next",
    description: "Upcoming project — stay tuned.",
    url: "https://secford.github.io/.../",
    image: "https://placehold.co/600x400/1a2248/6c8cff?text=New",
    tags: ["HTML", "CSS", "JS"],
  },
];
